### ISSUE TITLE
Update the MongoDB Kubernetes Operator to version v0.7.8

### ISSUE THREAD

**Issue by terenceq** [ibm-mas/ansible-devops#653]
## Update the MongoDB Kubernetes Operator to version v0.7.8

Due to security vulnerabilities with MongoDB Kubernetes Operator v0.7.0 the operator should be updated to the latest available version. Also, we should make sure to leverage the latest MongoDB 4.2.x and 4.4.x images

For more information about the MongoDB Kubernetes Operator see the following link:

https://github.com/mongodb/mongodb-kubernetes-operator

### Tasks to complete

- [ ] test upgrade scenario from 0.7.0 to 0.7.8
- [ ] new install test
- [ ] ensure that Mongo images can be updated independently of operator updates

**Comment by andrercm** [comment]
Hi @terenceq is this something you expect to be working anytime soon?

**Comment by whitfiea** [comment]
We will need to move from mongo 4.2 to 4.4 as 4.2 is EOL April 2023 https://www.mongodb.com/support-policy/lifecycles
